<?php

// include the page header
include('header.php');

?>

<!--/end of page header/ -->

<div id="gallery">

<img src="gallery/abstract/2003Houston023 copyweb.jpg" width="480" height="640" title="Houston 023" alt="This is the groundbreaking photograph that landed my first solo exhibition. It was taken in Houston, Texas, in the summer of 2003 during my travels around America. This piece is actually one of a set of three photographs, the other two are not shown on this website.">
<img src="gallery/abstract/2003MinneapolisStPaul367 copyweb.jpg" width="480" height="640" title = "Minneapolis 367" alt="Another pioneering photograph of my early architectural abstract series, this picture was taken in Minneapolis, Minnesota, and is one of a few black and white photographs I produced. This was also taken in 2003 on my American tour and was probably, what I consider, the first architectural abstract photograph I've ever taken.">
<img src="gallery/abstract/2004Ottowa050web.jpg" width="640" height="480" title = "Ottowa 050" alt="One of a few reflection pictures I took in Ottowa, Canada, this unique and complex photograph was taken in 2004 when I was on a tour of three Canadian cities in early May of 2004.">
<img src="gallery/abstract/2006Atlanta118web.jpg" width="427" height="640" title = "Atlanta 118" alt="A rusty looking imprint on a pristine building, this vertical photograph was taken when I was walking around in Atlanta, Georgia, just being a tourist. It was taken in 2006.">
<img src="gallery/abstract/2006Harvard001 copyweb.jpg" width="640" height="427" title = "Boston 001" alt="This is a photograph of the Harvard Medical Center in Boston, Massachusetts. I was seeing a friend who was studying in Boston for the summer in 2006. I had the chance to walk aimlessly around the town for some nice pictures.">
<img src="gallery/abstract/2006Harvard015 copy2web.jpg" width="427" height="640" title = "Boston 015" alt="This photograph was taken not far from the Harvard Medical Center on the same 2006 Boston summer trip. It is one of two photographs of cranes that I really like in my collection of building reflection photographs. The other one is not shown on this website.">
<img src="gallery/abstract/2007NYC007web.jpg" width="640" height="427" title = "New York 007" alt="New York City is known as the capital of photography, in addition to many other things people say. But it's true. I've taken many abstract building reflection photographs in this city, especially in Manhattan. This photograph was taken near Time Square in 2007.">
<img src="gallery/abstract/2007NYC013web.jpg" width="427" height="640" title = "New York 013" alt="Another photograph taken in New York City in 2007. This one was also near Times Square. It was part of an essential set of New York photographs in one of my gallery exhibitions.">
<img src="gallery/abstract/2007NYC029web.jpg" width="427" height="640" title = "New York 029 - Transition" alt="I rarely give titles to my photographs unless they are going to be printed in a book or be exhibited. This particular one is called 'Transition'. Looking carefully, one can see the individual offices in the building. In addition, the building seems to transition into something organic. With its colors and its unique composition, this is my favorite photograph of all time and is printed on a very limited edition. This too was taken in New York City in 2007.">
<img src="gallery/abstract/2007NYC220web.jpg" width="640" height="427" title = "New York 220" alt="Taken in 2007, this New York City building reflection is very different from my other ones because it reflects an old style architecture onto a modern glass skyscraper.">
<img src="gallery/abstract/2007NYC231web.jpg" width="640" height="427" title = "New York 231" alt="Another 2007 New York City piece. This one was printed and framed for an exhibition, then I gifted to someone dear. This photograph is not limited to large editions and it is one of few photographs that is gold-like.">
<img src="gallery/abstract/2007NYC279web.jpg" width="427" height="640" title = "New York 279 - Compression" alt="This photograph is called 'Compression' and was taken in New York City in 2007. It is only one of eight editions since it was exhibited and bought. This picture, as one can see, was taken at a unique angle giving the impression that the building is actually going though some kind of a time warp.">
<img src="gallery/abstract/2007NYC287web.jpg" width="640" height="427" title = "New York 287" alt="Continuing with 2007 New York City series, this photograph has many elements including different shades of blue and the curvature into a plane. Its form and composition contrast with my other architectural reflection photographs in that it's more three dimensional.">
<img src="gallery/abstract/2007NYC290web.jpg" width="640" height="427" title = "New York 290 - Water" alt="This photograph is my mother's favorite and many other people's as well. It has two titles. If displayed alone it is called 'Water'. There is another wave-like photograph that pairs very well with this one and if they were shown together this photograph would be called 'Fresh Water' while the other one would be called 'Mud'. 'Water' was also taken in New York City in 2007. 'Mud' is not shown on this website.">
<img src="gallery/abstract/2007NYC301web.jpg" width="427" height="640" title = "New York 301" alt="This is a somewhat simple photograph showing the building's curvature. I appreciate it simply because of its simplicity. This too was taken in New York City in 2007.">
<img src="gallery/abstract/2007NYC302web.jpg" width="640" height="427" title = "New York 302" alt="This interesting photograph has two very different looking buildings side by side, which is very unusual. They don't seem to belong together yet in a way they do. These buildings were also taken in New York City in 2007.">
<img src="gallery/abstract/2007NYC346web.jpg" width="640" height="427" title = "New York 346" alt="Another one of my favorites, this photograph is very complex and puzzling. It doesn't get much more abstract than this. Taken in 2007, New York City.">
<img src="gallery/abstract/2007Philadelphia181web.jpg" width="640" height="427" title = "Philadelphia 181" alt="Philadelphia, Pennsylvania, is the 5th largest U.S. city by population and it has some great architecture as well. This photograph contains many buildings all in one image. This picture was taken in 2007.">
<img src="gallery/abstract/2007Philadelphia184web.jpg" width="427" height="640" title = "Philadelphia 184" alt="Taken in 2007, this Philadelphia photograph is one of my top photographs. I love the chess piece-like imagery on the right and it goes well with the abstract lines to its left.">
<img src="gallery/abstract/2007Philadelphia192web.jpg" width="640" height="427" title = "Philadelphia 192" alt="In a very cubist style, this photograph captures the three dimensional nature of the buildings. Its colors coordinate very well with gold and blue. This picture has all the mystery of a great photograph. It was also taken in Philadelphia in 2007.">
<img src="gallery/abstract/2008JonNgDallas09web.jpg" width="640" height="427" title = "Dallas 09" alt="This building in Dallas, Texas, reminds of the side of a rusted old car. At least that's what the colors tell me. Nevertheless, it is a very abstract image, taken in 2008.">
<img src="gallery/abstract/2008JonNgDallas27web.jpg" width="640" height="427" title = "Dallas 27" alt="Taken in 2008, this building in Dallas, Texas, is very fabric-like, as if someone wove a quilt on the building. Never have I seen anything like this before.">
<img src="gallery/abstract/2009NYC030web.jpg" width="640" height="480" title ="New York 030" alt="Returning to New York City in 2009, this photograph is one of the few, if not the only photograph that contains something that is not reflection of a building, the scaffold on the lower left corner. This provides some realism to the image, contrary to most of my photographs.">
<img src="gallery/abstract/2009NYC041web.jpg" width="640" height="480" title = "New York 041" alt="This is a frontal shot of the reflection of a New York City building, which is an angle I rarely use. To me the feeling I get is colonial, like something out of the revolutionary war, except the reflecting building is a skyscraper. This picture was also taken in 2009.">
<img src="gallery/abstract/2009Roadtrip332web.jpg" width="640" height="480" title = "Charlotte 332" alt="I like to call this photograph 'Twins' because the buildings seem like they are brothers. I especially like the wavy lines intersecting the straight lines. Very juxtapositional. This picture was taken in Charlotte, North Carolina, in 2009 on a family road trip.">
<img src="gallery/abstract/2010Pittsburgh106web.jpg" width="480" height="640" title = "Pittsburgh 106" alt="Taken in 2010, Pittsburgh, Pennsylvania, this picture is a reflection of an old church across the street. I took many photographs at this spot and chose this particular one because the form of the building gave its uniqueness, where the curved edge meets the flat glass.">
<img src="gallery/abstract/2010Pittsburgh271web.jpg" width="640" height="480" title = "Pittsburgh 271" alt="This photograph was taken in downtown Pittsburgh. Its planes of lines are what makes me think this picture is worthy. It was taken in 2010 as well.">
<img src="gallery/abstract/2011Bethlehem57web.jpg" width="424" height="640" title = "Bethlehem 57" alt="This reflection photograph was not taken in a major city, like many of my other pictures. It was taken in a small town called Bethlehem in the Lehigh Valley area of Pennsylvania. It is a reflection of the Bethlehem Steel stacks on the facade of the Art Center across from it. This was taken in 2011.">
<img src="gallery/abstract/2011Bethlehem69web.jpg" width="424" height="640" title = "Bethlehem 69" alt="This is actually another photograph of the Bethlehem Steel but its composition and color are very different from other photographs taken at the same location. This picture was captured in 2011.">
<img src="gallery/abstract/2011Portland056web.jpg" width="640" height="424" title = "Portland 056" alt="Very few of my photographs have the color purple in them. This picture is not really an image of a tall skyscaper either. I like the ajar window, which gives the photograph its unique touch. Taken in Portland, Maine, in 2011 on a family vacation.">

</div><!-- close galley -->

<?php

// include the page footer
include('footer.php');

?> 